### ISSUE TITLE
Support for 0.7.1 react native version ?

### ISSUE THREAD

**Issue by piyushchauhan2011** [nick/react-native-carousel#15]
I'm using the react-native `0.7.1` version and tried to use your carousel for one of our app in production.

I'm getting this error:
![screen shot 2015-07-18 at 2 06 53 am](https://cloud.githubusercontent.com/assets/693487/8751679/ee2d4878-2cf1-11e5-9466-a4d056422bff.png)

**Comment by liuda101** [comment]
+1

**Comment by alinz** [comment]
This happens because `react-native-carousel` is not using `peerDependencies`. Well, I think @nick forgot to publish the latest one to npm. So for fixing this issue, you just have to fetch the library directly from github until nick publish this on npm.

in your `package.json`

replace this
```js
"react-native-carousel": "^0.3.3",
```
with this
```js
"react-native-carousel": "git+ssh://git@github.com:nick/react-native-carousel.git",
```

and you should be able to compile and run your code again.

**Comment by nick** [comment]
I just bumped the version so this should be fixed now

**Comment by alinz** [comment]
@nick Thanks!
